version: "3"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    build: ./infra/nginx
    ports:
      - 9000:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cansho_user
      - POSTGRES_PASSWORD=cansho_password
      - POSTGRES_DB=cansho

volumes:
  postgres_volume: